grpc:
  client:
    user-service:
      address: static://localhost:6565
      negotiationType: plaintext
    movie-service:
      address: static://localhost:7575
      negotiationType: plaintext
    audit-service:
      address: static://localhost:8585
      negotiationType: plaintext